version: '3.8'
services:
  streampark-console:
    image: apache/streampark:latest
    command: ${RUN_COMMAND}
    depends_on:
      - mysql11
    ports:
      - 10000:10000
      - 10030:10030
    env_file: .env
    volumes:
      - flink:/streampark/flink/${FLINK}
    privileged: true
    restart: unless-stopped
    networks:
      streampark-net:
        ipv4_address: 172.20.20.2


  flink-jobmanager:
    image: ${FLINK_IMAGE}
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - flink:/opt/flink
    env_file: .env
    restart: unless-stopped
    privileged: true
    networks:
      streampark-net:
        ipv4_address: 172.20.20.3

  flink-taskmanager:
    image: ${FLINK_IMAGE}
    depends_on:
      - flink-jobmanager
      # - mysql
    command: taskmanager
    deploy:
      replicas: 1
    env_file: .env
    restart: unless-stopped
    privileged: true
    networks:
      streampark-net:
        ipv4_address: 172.20.20.4


  mysql11:
    image: mysql:8.1
    restart: always
    ports:
      - '3316:3306'
    volumes:
      - mysqlv:/var/lib/mysql
    privileged: true
    userns_mode: keep-id
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      streampark-net:
        ipv4_address: 172.20.20.5

  kafka11:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      ### 通用配置
      # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      # 集群地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 设置broker最大内存，和初始内存
      #- KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      # 允许自动创建主题
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      ### broker配置
      # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.52.23.11:9092
      # broker.id，必须唯一
      - KAFKA_BROKER_ID=1
    networks:
      streampark-net:
        ipv4_address: 172.20.20.6

networks:
  streampark-net:
    ipam:
      config:
      - subnet: 172.20.20.0/16
        gateway: 172.20.20.1

volumes:
  flink:
  mysqlv:
  # kafkav:

