version: "2"
services:
  nginx:
    image: registry.cn-qingdao.aliyuncs.com/chs/chlw:nginx
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    external_links:
      - php
      - redis
    volumes_from:
      - php
  php:
    #image: registry.cn-hangzhou.aliyuncs.com/chs/php:alpine-workman
    image: registry.cn-hangzhou.aliyuncs.com/chs/php:swoole_git 
    ports:
      - "9000: "
    volumes:
      - ./www:/data1/www
    privileged: true
  redis:
    image: registry.cn-qingdao.aliyuncs.com/chs/chlw:redis
    ports:
      - "6379:6379"
  beanstalkd:
    image: registry.cn-qingdao.aliyuncs.com/chs/chlw:beanstalkd
    ports:
      - "11300:11300"
  elasticsearch:
    image: elasticsearch:5.6.7
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    volumes:
      - ./data/elastic/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
  mysql:
    #image: registry.cn-qingdao.aliyuncs.com/chs/chlw:mysql_shanghai
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
